version: 1
formatters:
  simple:
    format: '[%(levelname)s   | %(module)s           | L%(lineno)d] %(asctime)s: %(message)s | %(filename)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logs/pipeline.log
    level: INFO
    maxBytes: 10000
    backupCount: 1
loggers:
  pipeline:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: INFO
  handlers: [console, file]
